services:
  backend:
    volumes:
      - ./backend:/app
      - ./backend/target:/app/target

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
